"""User_Spot_Booking_Tables

Revision ID: 283d2e795947
Revises: 
Create Date: 2022-03-15 14:46:09.618995

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from datetime import datetime

# revision identifiers, used by Alembic.
revision = '283d2e795947'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    spot_table = op.create_table('spot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', postgresql.ENUM('Motorbike', 'Car', 'Truck', name='user_vehicle_type'), server_default='Car', nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_id'), 'spot', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('vehicle_type', postgresql.ENUM('Motorbike', 'Car', 'Truck', name='user_vehicle_type'), server_default='Car', nullable=False),
    sa.Column('license_plate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('booking_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('license_plate', sa.String(), nullable=True),
    sa.Column('spot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spot_id'], ['spot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_dates_id'), 'booking_dates', ['id'], unique=False)
    # ### end Alembic commands ###
    spots = list()

    spots =  add_vehicle(spots,'Motorbike' , 10)
    spots =  add_vehicle(spots,'Car' , 20)
    spots =  add_vehicle(spots,'Truck' , 10)
        
    op.bulk_insert(spot_table, spots)



def add_vehicle(spots, type, total):
    offset = len(spots)
    for i in range(1,total+1):
        spots.append({   
            'id':i+offset,
            'created_at': datetime.now(),
            'name': type[0]+str(i),
            'type':type,
            'disabled':False
        })
    return spots

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_dates_id'), table_name='booking_dates')
    op.drop_table('booking_dates')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_spot_id'), table_name='spot')
    op.drop_table('spot')
    # ### end Alembic commands ###
