#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e

S2I_EXE=s2i
if [ -z $(type -P "$S2I_EXE") ]; then
  echo -e "The ${S2I_EXE} executable is needed and not on your path."
  echo -e "It can be downloaded from here: https://github.com/openshift/source-to-image"
  echo -e "Make sure you place it in a directory on your path."
  exit 1
fi

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME-parking}"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF

  Usage: $0 {start|stop|build|rm}

  Options:

  build - Build the docker images for the project.
          You need to do this first, since the builds require
          a combination of Docker and S2I builds.

  start - Creates the application containers from the built images
          and starts the services based on the docker-compose.yml file.

          You can pass in a list of containers to start.  
          By default all containers will be started.
          
          Examples:
          $0 start         

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.

  rm - Removes any existing application containers.
EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Default Settings: 
# -----------------------------------------------------------------------------------------------------------------
DEFAULT_CONTAINERS="db api web"
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
build-all() {
  build-web
  build-api
}

build-web() {
  #
  # web
  #
  # The runtime image is used for the final runtime image.
  # The web-artifacts image is used to build the artifacts for the vue distribution.
  # The web image is copy of the runtime image complete with a copy of the build artifacts.
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building the ${COMPOSE_PROJECT_NAME}-runtime image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t ${COMPOSE_PROJECT_NAME}'-runtime' \
    -f './nginx-runtime/Dockerfile' './nginx-runtime/'
  echo -e "===================================================================================================="
  
  echo -e "\n\n===================================================================================================="
  echo -e "Building the ${COMPOSE_PROJECT_NAME}-web-artifacts image using s2i (WEB_BASE_HREF: '${WEB_BASE_HREF}') ..."
  echo -e "-----------------------WEB_BASE_HREF=${WEB_BASE_HREF}-----------------------------------------------------------------------------"
  ${S2I_EXE} build \
    --copy \
    -e  PUBLIC_URL=${DEFAULT_BASE_URL}\
    '../web' \
    'centos/nodejs-10-centos7:10' \
    ${COMPOSE_PROJECT_NAME}'-web-artifacts'
  echo -e "===================================================================================================="

  echo -e "\n\n===================================================================================================="
  echo -e "Building the ${COMPOSE_PROJECT_NAME}-web image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t ${COMPOSE_PROJECT_NAME}'-web' \
    -f './vue-on-nginx/Dockerfile' './vue-on-nginx/'
  echo -e "===================================================================================================="
}

build-api() {
  #
  # api
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building ${COMPOSE_PROJECT_NAME}-api image using s2i ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  ${S2I_EXE} build \
    --copy \
    '../api' \
    'centos/python-38-centos7' \
    ${COMPOSE_PROJECT_NAME}'-api'
  echo -e "===================================================================================================="
}


configureEnvironment () {
  for arg in $@; do
    case "$arg" in
      *=*)
        export ${arg}
        ;;  
    esac
  done
  
  # db
  export POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE-your_db_name}
  export POSTGRESQL_USER=${POSTGRESQL_USER-your_db_user}
  export POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD-your_db_password}

  # api
  export API_HTTP_PORT=${API_HTTP_PORT-8080}
  export DATABASE_SERVICE_NAME="db"
  export DATABASE_ENGINE="postgresql"
  export DATABASE_NAME=${POSTGRESQL_DATABASE}
  export DATABASE_USER=${POSTGRESQL_USER}
  export DATABASE_PASSWORD=${POSTGRESQL_PASSWORD}
  export JWT_SECRET_KEY=${JWT_SECRET_KEY-vVSdfa1GhvsE23ghrKJTRRkjtdfg4234DRfgtTREef525e}
  export DATA_SECURITY_KEY=${DATA_SECURITY_KEY-D34FERdsur4D7HFgGDghFGRE4df3h64GGHRqfsdfguFFH65GK}
  export DEFAULT_BASE_URL=${DEFAULT_BASE_URL-/parking-app}  
  
  # web
  export WEB_HTTP_PORT=${WEB_HTTP_PORT-8081}
  export API_URL=${API_URL-http://api:8080/api}
  export WEB_BASE_HREF=${DEFAULT_BASE_URL}
  export PUBLIC_URL=${DEFAULT_BASE_URL}
  export IpFilterRules='#allow all; deny all;'
  export RealIpFrom='127.0.0.0/16'
}

getStartupParams() {
  CONTAINERS=""
  ARGS="--force-recreate"

  for arg in $@; do
    case "$arg" in
      *=*)
        # Skip it
        ;;  
     -*)
        ARGS+=" $arg";;
      *)
        CONTAINERS+=" $arg";;
    esac
  done

  if [ -z "$CONTAINERS" ]; then
    CONTAINERS="$DEFAULT_CONTAINERS"
  fi
  echo ${ARGS} ${CONTAINERS}
}

deleteVolumes() {
  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  echo "Stopping and removing any running containers ..."
  docker-compose rm -svf >/dev/null

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern})

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} |  xargs docker volume rm
  else
    echo "No project volumes exist."
  fi
}

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

functionExists() {
  (
    if [ ! -z ${1} ] && type ${1} &>/dev/null; then
      return 0
    else
      return 1
    fi
  )
}

clean() {
  docker rmi --force ${COMPOSE_PROJECT_NAME}-runtime ${COMPOSE_PROJECT_NAME}-web-artifacts ${COMPOSE_PROJECT_NAME}-web ${COMPOSE_PROJECT_NAME}-web-dev ${COMPOSE_PROJECT_NAME}-api
  docker image prune --force
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
COMMAND=$(toLower ${1})
shift

case "$COMMAND" in
  start)
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    docker-compose up ${_startupParams}
    ;;  
  stop)
    configureEnvironment $@
    docker-compose stop
    ;;
  rm|down)
    configureEnvironment $@
    deleteVolumes
    ;;
  clean)
    configureEnvironment $@
    clean
    ;;
  build)
    buildImage=$(toLower ${1})
    shift || buildImage=all
    buildImage=$(echo ${buildImage} | sed s~^${COMPOSE_PROJECT_NAME}-~~)
    case "$buildImage" in
      *=*)
        buildImage=all
        ;;
    esac

    if functionExists "build-${buildImage}"; then
      configureEnvironment $@
      eval "build-${buildImage}"
    else
      echo -e "Error:\nThe build function, build-${buildImage}, does not exist.  Please check your build parameters and try again.\nUse '-h' to get full help details."
      exit 1
    fi
    ;;
  *)
    usage
esac

popd >/dev/null
